### ISSUE TITLE
Script doesnt work since Fritz OS 7.20 Update

### ISSUE THREAD

**Issue by accupatz** [schlomo/fritzbox-internet-ticket#1]
Hi,

I think  pp_ticket.lua url has changed:

/root/fritzbox-internet-ticket/fritzbox-get-internet-tickets.py 

<p>Die angegebene URL wurde nicht gefunden. Sie werden auf die Startseite der FRITZ!Box weitergeleitet.</p>
<p>Falls Sie nicht automatisch auf die Startseite der FRITZ!Box weitergeleitet werden, klicken Sie <a href="/">hier</a>.</p>

DEBUG: []
Could not find any Internet tickets.

[debug_log.txt](https://github.com/schlomo/fritzbox-internet-ticket/files/5134940/debug_log.txt)

**Comment by schlomo** [comment]
Oh, cool. I wasn't aware of somebody using this. I am still waiting for 7.20 on my FB 7590 and will be happy to investigate this after I get the update. Till then I'd appreciate a patch from you.

**Comment by schlomo** [comment]
Ah, I can already update. Will have a look in the evening.

**Comment by schlomo** [comment]
The problem was that AVM removed the dedicated page for printing the tickets and replaced that with a Javascript generated version. No problem, we can simply scrape the data XHR directly.

I'd be happy to hear from you more about your use case for this software, didn't actually expect anybody to use that. Do you also use the Google Form upload feature and the GCP Pub/Sub part? Care to share? You can reach out [privately](https://consulting.schlomo.schapiro.org/) if you prefer.
